# Generated by Django 2.1.5 on 2020-03-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='cafeImg',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
