# Generated by Django 2.1.5 on 2020-03-06 04:59

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('main', '0002_cafe_cafeimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafe',
            old_name='description',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='cafe',
            old_name='cafeImg',
            new_name='mainphoto',
        ),
        migrations.RenameField(
            model_name='cafe',
            old_name='cafeName',
            new_name='name',
        ),
        migrations.AddField(
            model_name='cafe',
            name='insta',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='lng',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='locate',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='modifiedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='phone',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='publishedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='subphoto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='cafe',
            name='tag',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
